### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by ghost** [browsertap/ditto.js#22]
I've installed ditto.js globally. I'm trying to listen to changes on a certain file/directory, by running this command from the terminal:

ditto-proxy 127.0.0.1 --watch= /path/to/my/file --port=8080

When I open the browser with URL http://127.0.0.1:8080/index.html I get the following error: "Error: connect ECONNREFUSED".

I have tried "localhost" instead of "127.0.0.1", and have tried different (available) ports.

For the --watch parameter, should it be the name of a file or a directory?

Any idea why I would be getting this error?

**Comment by crcn** [comment]
So the problem was that the protocol wasn't included. I've fixed the command line interface so you don't need it. Here's what I used to test:

```
 ditto-proxy 127.0.0.1:8081 --verbose --port=8080
```

Lmk if that works!

Also, the watch parameter should be a pattern. It can be something like:

```
/path/to/my/file/**/*.css
/path/to/my/file/index.html
```

Be sure to add `**` if you want to recursively watch files.

**Comment by ghost** [comment]
When I try with: ditto-proxy http://127.0.0.1:8081 --watch=/Users/casper/source/zapboard/index.html --port=8080 --verbose

Using http://localhost:8080/index.html I get "Error: connect ECONNREFUSED" in the terminal
Using http://localhost:8081/index.html I get "Oops! Google Chrome could not connect to localhost:8081" in the browser.

**Comment by crcn** [comment]
Sounds like you don't have a server running on port `8081`. the `--port` parameter is used for ditto.

**Comment by ghost** [comment]
Okay, I'm much closer now, thanks. :)

I've installed http-server node module, which is now serving the static pages. So, now when I launch "http://localhost:8080/" in the browser, it shows the page correctly, and no more errors in the console.

Now, I open the index.html file in my IDE, and make some simple text changes. Once I save the file, get the following in the console: "changed: /Users/casper/source/zapboard/index.html". So, obviously ditto is picking up the changes.

So, I have the following questions:

1) Is the browser supposed to refresh automatically once I save the html file?
2) Why is the ditto console printing the same message ("changed: /Users/casper/source/zapboard/index.html") multiple times for a single change? - almost like it's going into a loop.

**Comment by crcn** [comment]
1 - Not supported yet, but will very soon. Right now the following is supported:
- css changes
- user interactions - open up another browser and scroll, type, navigate around
- console logs are sent back to terminal

2 - I'll take a look at this - sounds like a bug.

**Comment by ghost** [comment]
Please ignore question 2. It's actually my IDE that went into a "saving" loop.
